#!/usr/bin/env bash
# Fails if a page links to a repository that is archived.
#
#   scripts/check-archived-refs.sh
#
# asobi has the same check over its guides. The site needed its own because
# most of its pages are NOT generated from those guides: 29 are, and about 45
# are hand-written and regenerated by nothing. That asymmetry is how seven
# pages came to tell readers to pull ghcr.io/widgrensit/asobi_lua months after
# the rename, and how /lua kept a "View on GitHub" button pointing at an
# archived repo - all while the guides themselves were correct.
#
# Deliberately not a link checker. The links resolve: an archived repo is
# read-only, still public, still indexed. Nothing 404s. The advice is simply
# wrong, and only a human or this script will notice.
set -euo pipefail

# repo | what to say instead. Add a row in the same PR that archives something.
ARCHIVED=(
  "asobi_lua|the Lua runtime is part of asobi - link widgrensit/asobi, and the image is ghcr.io/widgrensit/asobi"
  "asobi_admin|the operator console ships in asobi - link /docs/console"
)

# Two exemptions.
#
# Blog posts: a dated post said what was true when it was published, and
# rewriting that to keep a linter quiet is fabricating history.
#
# Generated views: their source is asobi's guides, which have their own
# archived-reference check, and a guide legitimately names the old thing in
# order to tell you to stop using it - the glossary's whole job on this point.
# Fixing those here would also be undone by the next regeneration.
generated="$(grep -oE 'asobi_site_docs_[a-z_]+_view' scripts/gen-docs.sh | sort -u | paste -sd'|')"
EXEMPT="blog_posts|${generated}"

fails=0
for entry in "${ARCHIVED[@]}"; do
  repo="${entry%%|*}"
  advice="${entry#*|}"

  hits="$(grep -rnE "github\.com/[a-z-]+/${repo}\b|ghcr\.io/[a-z-]+/${repo}\b" src/ 2>/dev/null \
          | grep -vE "$EXEMPT" || true)"

  if [ -n "$hits" ]; then
    printf '\n%s is archived, but the site still points at it:\n\n' "$repo"
    printf '%s\n' "$hits" | sed 's/^/  /'
    printf '\n  Say instead: %s\n' "$advice"
    fails=$((fails + 1))
  fi
done

if [ "$fails" -gt 0 ]; then
  printf '\n%d archived repository reference(s) on the site.\n' "$fails" >&2
  exit 1
fi

echo "no page points at an archived repository"
